
import React from 'react';

interface ImageDisplayProps {
  generatedImage: string | null;
}

const ImageDisplay: React.FC<ImageDisplayProps> = ({ generatedImage }) => {
  if (!generatedImage) {
    return (
      <div className="text-center text-gray-400">
        <svg xmlns="http://www.w3.org/2000/svg" className="mx-auto h-24 w-24 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
        <h3 className="mt-4 text-xl font-semibold">Your Image Appears Here</h3>
        <p className="mt-1 text-sm">Enter a prompt and click "Generate" to see the magic happen!</p>
      </div>
    );
  }

  return (
    <div className="w-full h-full flex flex-col items-center justify-center">
        <img
          src={generatedImage}
          alt="Generated by AI"
          className="rounded-lg shadow-2xl object-contain max-w-full max-h-full"
          style={{ maxHeight: 'calc(100vh - 200px)'}}
        />
        <a 
          href={generatedImage} 
          download="ai-generated-image.png"
          className="mt-4 inline-block bg-green-600 text-white font-bold py-2 px-6 rounded-lg hover:bg-green-700 transition-colors"
        >
          Download Image
        </a>
    </div>
  );
};

export default ImageDisplay;
